upstream backend_servers {
    # Use localhost because containers run with --network host
    server 127.0.0.1:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;
    }
}
